### ISSUE TITLE
mmap test failed

### ISSUE THREAD

**Issue by OlliV** [Zeke-OS/zeke#95]
# TEST_MMAP
    -TEST_MMAP_ANON
    -TEST_MMAP_ANON_FIXED
    -TEST_MMAP_FILE
    0:HAL/ARM11/ARM11_MMU.C:603: DAB HANDLING FAILED: -2
    PSR = 0X20000110
    R0  = 0X00000400
    R1  = 0X00000400
    R2  = 0X00000400
    R3  = 0X00902E74
    R4  = 0XB8E00420
    R5  = 0X10001A40
    R6  = 0XB8E00420
    R7  = 0X00000001
    R8  = 0X00902F38
    R9  = 0X1001E0B4
    R10 = 0X0FFFF000
    R11 = 0X00902E80
    R12 = 0X0000000B
    SP  = 0X00902E70
    LR  = 0X10001B48
    PC  = 0X10001B64
    0:HAL/ARM11/ARM11_MMU.C:675: FATAL DAB
    PC: 0X10001B64
    FSR: 0X00000007 (PAGE TRANSLATION)
    FAR: 0XB8E00458
    PROC INFO:
    PID: 7
    TID: 7
    INSYS: 0
    0:HAL/ARM11/ARM11_MMU.C:677: OOPS, KERNEL PANIC
    0:HAL/ARM11/ARM11_MMU.C:677: CAN'T HANDLE DATA ABORTqemu: terminating on signal 2 from pid 780

**Comment by Tsarpf** [comment]
Where is the fix? I must know?!?!

**Comment by OlliV** [comment]
6043df855ba6d80eaf8abbe483c96a66f1dedaf
de35134bd89039fc40cd6923270fdb9061c3a734
16f717fc02572611510a37b9e27b60427836b52c
